### ISSUE TITLE
Week-1 - Data Master Pegawai

### ISSUE THREAD

**Issue by ade-ridwan** [ade-ridwan/presensi-duta-web#10]
```
git fetch origin
git checkout data-master-pegawai
```

**Comment by ade-ridwan** [comment]
**Fitur Dasar**
- [x] Buat Controller Admin/PegawaiController
- [x] Buat Route web.php untuk pegawai
- [x] Buat View Crud Untuk Pegawai

**Tantangan / Advanced**

- [x] Pada saat pegawai ditambahkan harus terbuat juga data di tabel user

**Comment by tikawahyu** [comment]
mas, ada contoh / langkah yang ada FK nya?

**Comment by ade-ridwan** [comment]
Boleh coba di cek yg di Menu User Bu @tikawahyu , Kemarin sudah ditambahkan menu User. Atau bila ada kendala yg kolom FK nya boleh dilewati dulu bu. Jadi hanya ada inputan kolom tanpa yg tipe FK.

**Comment by tikawahyu** [comment]
menu usernya di tampilanku ga da ya mas

**Comment by ade-ridwan** [comment]
Coba di checkout dulu bu branch nya ke issue yg sekarang

**Comment by tikawahyu** [comment]
sudah mas, ini malahan sudah bikin controller
