### ISSUE TITLE
Membuat Migration Tabel

### ISSUE THREAD

**Issue by ade-ridwan** [ade-ridwan/presensi-duta-web#2]
```
git fetch origin
git checkout add-migration-bu-tika
```

**Comment by tikawahyu** [comment]
Membuat Migration
- [x] tb_ruang
- [x] tb_waktu_absensi
- [x] tb_guru_mapel
- [x] tb_waktu_pelajaran
- [x] tb_mapel
- [x] tb_role
- [x] tb_guru_piket
- [x] tb_jadwal_pelajaran
- [x] tb_absen_mengajar
- [x] tb_users
- [x] tb_pegawai
- [x] tb_kehadiran_pegawai
